<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Capturing screenshot]]>
    </line>
    <line>
      <![CDATA[Customer Login successfully executed]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="C:\Users\workspace\Documents\screenshot\error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="C:\Users\workspace\Documents\screenshot\error.jpg"><img src="C:\Users\workspace\Documents\screenshot\error.jpg" height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Bank XYZ Automation Test" duration-ms="15556" started-at="2021-07-26T10:31:42 CAT" finished-at="2021-07-26T10:31:57 CAT">
    <groups>
    </groups>
    <test name="Test" duration-ms="15556" started-at="2021-07-26T10:31:42 CAT" finished-at="2021-07-26T10:31:57 CAT">
      <class name="org.malitcode.test.ManagerLoginTest">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:org.malitcode.test.ManagerLoginTest@5a4041cc]" name="setUp" is-config="true" duration-ms="11908" started-at="2021-07-26T10:31:42 CAT" finished-at="2021-07-26T10:31:54 CAT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginManager()[pri:0, instance:org.malitcode.test.ManagerLoginTest@5a4041cc]" name="loginManager" duration-ms="3013" started-at="2021-07-26T10:31:54 CAT" finished-at="2021-07-26T10:31:57 CAT">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Login Not Succesfful]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Login Not Succesfful
at junit.framework.Assert.fail(Assert.java:47)
at org.malitcode.test.ManagerLoginTest.loginManager(ManagerLoginTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Capturing screenshot]]>
            </line>
            <line>
              <![CDATA[Customer Login successfully executed]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="C:\Users\workspace\Documents\screenshot\error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="C:\Users\workspace\Documents\screenshot\error.jpg"><img src="C:\Users\workspace\Documents\screenshot\error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginManager -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:org.malitcode.test.ManagerLoginTest@5a4041cc]" name="tearDown" is-config="true" duration-ms="511" started-at="2021-07-26T10:31:57 CAT" finished-at="2021-07-26T10:31:57 CAT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.malitcode.test.ManagerLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Bank XYZ Automation Test -->
</testng-results>
